export const PERMISSIONS = {
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_EDIT: 'products.edit',
  PRODUCTS_DELETE: 'products.delete',
  PRODUCTS_SET_COST: 'products.setCost',
  STOCK_ADJUST: 'stock.adjust',
  PERMITS_WITHDRAW: 'permits.withdraw',
  PERMITS_SUPPLY: 'permits.supply',
  SCAN_USE: 'scan.use',
  LOGS_VIEW: 'logs.view',
  STOCKTAKE_CREATE: 'stocktake.create',
  STOCKTAKE_APPROVE: 'stocktake.approve',
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',
  USERS_VIEW: 'users.view',
  USERS_MANAGE: 'users.manage',
  ROLES_VIEW: 'roles.view',
  ROLES_EDIT: 'roles.edit',
  SUPPLIERS_VIEW: 'suppliers.view',
  SUPPLIERS_CREATE: 'suppliers.create',
  SUPPLIERS_EDIT: 'suppliers.edit',
  SUPPLIERS_DELETE: 'suppliers.delete',
  PURCHASE_ORDERS_VIEW: 'purchase_orders.view',
  PURCHASE_ORDERS_CREATE: 'purchase_orders.create',
  PURCHASE_ORDERS_EDIT: 'purchase_orders.edit',
  PURCHASE_ORDERS_RECEIVE: 'purchase_orders.receive',
  CLIENTS_VIEW: 'clients.view',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_EDIT: 'clients.edit',
  CLIENTS_DELETE: 'clients.delete',
  PRODUCTS_IMPORT: 'products.import',
  PRODUCTS_EXPORT: 'products.export',
  RESERVATIONS_VIEW: 'reservations.view',
  RESERVATIONS_CREATE: 'reservations.create',
  RESERVATIONS_EDIT: 'reservations.edit',
  RESERVATIONS_CANCEL: 'reservations.cancel',
  RESERVATIONS_FULFILL: 'reservations.fulfill',
  PURCHASE_ORDERS_SUBMIT: 'purchase_orders.submit',
  PURCHASE_ORDERS_APPROVE: 'purchase_orders.approve',
  PURCHASE_ORDERS_SEND: 'purchase_orders.send',
  PURCHASE_ORDERS_CANCEL: 'purchase_orders.cancel',
  PURCHASE_ORDERS_CLOSE: 'purchase_orders.close',
  SALES_ORDERS_VIEW: 'sales_orders.view',
  SALES_ORDERS_CREATE: 'sales_orders.create',
  SALES_ORDERS_EDIT_DRAFT: 'sales_orders.edit_draft',
  SALES_ORDERS_CONFIRM: 'sales_orders.confirm',
  SALES_ORDERS_PROCESS: 'sales_orders.process',
  SALES_ORDERS_SHIP: 'sales_orders.ship',
  SALES_ORDERS_DELIVER: 'sales_orders.deliver',
  SALES_ORDERS_APPROVE: 'sales_orders.approve',
  SALES_ORDERS_REJECT: 'sales_orders.reject',
  SALES_ORDERS_CLOSE: 'sales_orders.close',
  SALES_ORDERS_CANCEL: 'sales_orders.cancel',
  RETURNS_VIEW: 'returns.view',
  RETURNS_CREATE: 'returns.create',
  RETURNS_APPROVE: 'returns.approve',
  RETURNS_RECEIVE: 'returns.receive',
  RETURNS_REJECT: 'returns.reject',
  RETURNS_CLOSE: 'returns.close',
  RETURNS_REFUND: 'returns.refund',
  WAREHOUSES_VIEW: 'warehouses.view',
  WAREHOUSES_CREATE: 'warehouses.create',
  WAREHOUSES_EDIT: 'warehouses.edit',
  TRANSFERS_VIEW: 'transfers.view',
  TRANSFERS_CREATE: 'transfers.create',
  TRANSFERS_EXECUTE: 'transfers.execute',
  TRANSFERS_CANCEL: 'transfers.cancel',
  PRESENTATION_VIEW: 'presentation.view',
  PRESENTATION_EDIT: 'presentation.edit',
  PRICE_LISTS_VIEW: 'price_lists.view',
  PRICE_LISTS_MANAGE: 'price_lists.manage',
  PRICE_LISTS_OVERRIDE: 'price_lists.override',
  ALERTS_VIEW: 'alerts.view',
  ALERTS_MANAGE: 'alerts.manage',
  ANOMALIES_VIEW: 'anomalies.view',
  ANOMALIES_RUN: 'anomalies.run',
  ANOMALIES_RESOLVE: 'anomalies.resolve',
  TIMELINE_VIEW: 'timeline.view',
  SETTINGS_VIEW: 'settings.view',
  SETTINGS_MANAGE: 'settings.manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS);

export const DEFAULT_ROLES: Record<string, { displayName: string; description: string; permissions: Permission[] }> = {
  owner: {
    displayName: 'المالك',
    description: 'صلاحيات كاملة على النظام — إدارة المستخدمين والصلاحيات والمخزون والتقارير',
    permissions: ALL_PERMISSIONS,
  },
  manager: {
    displayName: 'مدير',
    description: 'إدارة المنتجات والتوريد والصرف والمسح والتقارير — لا يستطيع إدارة المستخدمين',
    permissions: [
      PERMISSIONS.PRODUCTS_VIEW,
      PERMISSIONS.PRODUCTS_CREATE,
      PERMISSIONS.PRODUCTS_EDIT,
      PERMISSIONS.PRODUCTS_DELETE,
      PERMISSIONS.STOCK_ADJUST,
      PERMISSIONS.PERMITS_WITHDRAW,
      PERMISSIONS.PERMITS_SUPPLY,
      PERMISSIONS.SCAN_USE,
      PERMISSIONS.LOGS_VIEW,
      PERMISSIONS.STOCKTAKE_CREATE,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.SUPPLIERS_VIEW,
      PERMISSIONS.SUPPLIERS_CREATE,
      PERMISSIONS.SUPPLIERS_EDIT,
      PERMISSIONS.SUPPLIERS_DELETE,
      PERMISSIONS.PURCHASE_ORDERS_VIEW,
      PERMISSIONS.PURCHASE_ORDERS_CREATE,
      PERMISSIONS.PURCHASE_ORDERS_EDIT,
      PERMISSIONS.PURCHASE_ORDERS_RECEIVE,
      PERMISSIONS.CLIENTS_VIEW,
      PERMISSIONS.CLIENTS_CREATE,
      PERMISSIONS.CLIENTS_EDIT,
      PERMISSIONS.CLIENTS_DELETE,
      PERMISSIONS.RESERVATIONS_VIEW,
      PERMISSIONS.RESERVATIONS_CREATE,
      PERMISSIONS.RESERVATIONS_EDIT,
      PERMISSIONS.RESERVATIONS_CANCEL,
      PERMISSIONS.RESERVATIONS_FULFILL,
      PERMISSIONS.PURCHASE_ORDERS_SUBMIT,
      PERMISSIONS.PURCHASE_ORDERS_APPROVE,
      PERMISSIONS.PURCHASE_ORDERS_SEND,
      PERMISSIONS.PURCHASE_ORDERS_CANCEL,
      PERMISSIONS.PURCHASE_ORDERS_CLOSE,
      PERMISSIONS.SALES_ORDERS_VIEW,
      PERMISSIONS.SALES_ORDERS_CREATE,
      PERMISSIONS.SALES_ORDERS_EDIT_DRAFT,
      PERMISSIONS.SALES_ORDERS_CONFIRM,
      PERMISSIONS.SALES_ORDERS_PROCESS,
      PERMISSIONS.SALES_ORDERS_SHIP,
      PERMISSIONS.SALES_ORDERS_DELIVER,
      PERMISSIONS.SALES_ORDERS_CLOSE,
      PERMISSIONS.SALES_ORDERS_CANCEL,
      PERMISSIONS.RETURNS_VIEW,
      PERMISSIONS.RETURNS_CREATE,
      PERMISSIONS.RETURNS_RECEIVE,
      PERMISSIONS.RETURNS_CLOSE,
      PERMISSIONS.WAREHOUSES_VIEW,
      PERMISSIONS.WAREHOUSES_CREATE,
      PERMISSIONS.WAREHOUSES_EDIT,
      PERMISSIONS.TRANSFERS_VIEW,
      PERMISSIONS.TRANSFERS_CREATE,
      PERMISSIONS.TRANSFERS_EXECUTE,
      PERMISSIONS.TRANSFERS_CANCEL,
      PERMISSIONS.PRESENTATION_VIEW,
      PERMISSIONS.PRESENTATION_EDIT,
      PERMISSIONS.PRICE_LISTS_VIEW,
      PERMISSIONS.PRICE_LISTS_MANAGE,
      PERMISSIONS.PRICE_LISTS_OVERRIDE,
      PERMISSIONS.ALERTS_VIEW,
      PERMISSIONS.ALERTS_MANAGE,
      PERMISSIONS.ANOMALIES_VIEW,
      PERMISSIONS.ANOMALIES_RUN,
      PERMISSIONS.TIMELINE_VIEW,
      PERMISSIONS.SETTINGS_VIEW,
    ],
  },
  viewer: {
    displayName: 'متابع',
    description: 'عرض المخزون والتقارير وأوامر البيع فقط — لا يستطيع التعديل أو الإنشاء',
    permissions: [
      PERMISSIONS.PRODUCTS_VIEW,
      PERMISSIONS.LOGS_VIEW,
      PERMISSIONS.REPORTS_VIEW,
      PERMISSIONS.REPORTS_EXPORT,
      PERMISSIONS.SALES_ORDERS_VIEW,
      PERMISSIONS.RETURNS_VIEW,
      PERMISSIONS.WAREHOUSES_VIEW,
      PERMISSIONS.TRANSFERS_VIEW,
      PERMISSIONS.PRESENTATION_VIEW,
      PERMISSIONS.PRICE_LISTS_VIEW,
      PERMISSIONS.ALERTS_VIEW,
      PERMISSIONS.ANOMALIES_VIEW,
      PERMISSIONS.TIMELINE_VIEW,
      PERMISSIONS.SETTINGS_VIEW,
    ],
  },
};
